{{ $concert->title }}
{{ $concert->subtitle }}
{{ $concert->formatted_start_time }}
{{ $concert->formatted_date }}
{{ $concert->ticket_price_in_dollars }}
{{ $concert->venue }}
{{ $concert->venue_address }}
{{ $concert->city }}
{{ $concert->state }}
{{ $concert->zip }}
{{ $concert->additional_information }}
